---
resources:
- name: src
  type: git
  check_every: 1m
  source:
    uri: https://github.com/YaserBensiali/concourse-demos
    branch: main

jobs:
- name: whats-here-mdear
  plan:
    - get: src
      trigger: true
    - task: list
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: alpine
            tag: latest
        inputs:
        - name: src
        run:
          path: /bin/sh
          args:
          - -exc
          - |
            cd src
            ls

